<?php

declare(strict_types=1);

namespace Acme\SpryngMessaging\Tools;

use RuntimeException;

require __DIR__ . '/lib/HtmlDocParser.php';
require __DIR__ . '/lib/YamlWriter.php';

/**
 * Derives an OpenAPI 3.1 document from the documentation mirror.
 *
 * The portal does not publish a machine-readable specification, so this reads
 * what it does publish - prose, parameter tables, cURL samples and example
 * responses - and reconstructs one. Where two sources of truth disagree (the
 * "URL & method" prose versus the cURL sample) the sample wins, because it is
 * generated rather than typed, and every disagreement is listed in
 * docs/api/CONFLICTS.md so it can be checked by hand.
 *
 * Usage:
 *   php tools/build-openapi.php [docs-dir] [output-file]
 */
final class OpenApiBuilder
{
    private const SERVER_URL   = 'https://api.spryng.nl/v2';
    private const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];

    /** @var list<string> */
    private array $notes = [];

    /** @var array<string, true> */
    private array $operationIds = [];

    /** @var list<array<string, mixed>> */
    private array $errorExamples = [];

    public function __construct(
        private readonly string $docsDir,
        private readonly string $outputFile,
    ) {
    }

    public function run(): void
    {
        $paths = [];
        $tags  = [];

        foreach ($this->pages() as $page) {
            $route      = $page['route'];
            $categoryId = $page['category'];

            $endpoint = $this->endpoint($route, $page['id']);
            if ($endpoint === null) {
                $this->note(sprintf('%s: no endpoint documented, left out of the spec.', $page['id']));
                continue;
            }

            $tags[$categoryId] = true;

            $operation = $this->operation($route, $page, $endpoint);
            $path      = $endpoint['path'];
            $method    = strtolower($endpoint['method']);

            if (isset($paths[$path][$method])) {
                $this->note(sprintf('%s: %s %s is already described elsewhere, kept the first one.', $page['id'], strtoupper($method), $path));
                continue;
            }

            $paths[$path][$method] = $operation;
        }

        ksort($paths);

        $document = [
            'openapi' => '3.1.0',
            'info'    => [
                'title'       => 'Spryng Messaging v2 API',
                'version'     => $this->revision(),
                'license'     => ['name' => 'MIT', 'identifier' => 'MIT'],
                'description' => implode("\n", [
                    'Reconstructed from the Spryng developer portal at https://developer.spryng.nl.',
                    '',
                    'Generated by tools/build-openapi.php from the mirror in docs/api. Spryng does',
                    'not publish an OpenAPI document, so schemas are inferred from the parameter',
                    'tables and example payloads in the documentation. Treat it as a close reading',
                    'of the docs, not as a contract from the vendor.',
                ]),
            ],
            'servers'    => [['url' => self::SERVER_URL]],
            'security'   => [['apiKey' => []]],
            'tags'       => $this->tagList(array_keys($tags)),
            'paths'      => $paths,
            'components' => [
                'securitySchemes' => [
                    'apiKey' => [
                        'type'        => 'apiKey',
                        'in'          => 'header',
                        'name'        => 'X-Api-Key',
                        'description' => 'API key generated in the Spryng portal.',
                    ],
                ],
                'schemas' => ['ErrorResponse' => $this->errorSchema()],
            ],
        ];

        file_put_contents($this->outputFile, YamlWriter::dump($document));
        $this->writeEndpointIndex($paths);
        $this->writeConflictReport(count($paths));

        fwrite(STDOUT, sprintf(
            "Wrote %s (%d paths, %d notes)\n",
            $this->outputFile,
            count($paths),
            count($this->notes)
        ));
    }

    /**
     * @return list<array{id: string, category: string, page: string, route: array<string, mixed>}>
     */
    private function pages(): array
    {
        $rawDir = $this->docsDir . '/raw';
        if (!is_dir($rawDir)) {
            throw new RuntimeException(sprintf('%s does not exist; run tools/fetch-docs.php first.', $rawDir));
        }

        $pages = [];

        foreach (glob($rawDir . '/*', GLOB_ONLYDIR) ?: [] as $categoryDir) {
            foreach (glob($categoryDir . '/*.json') ?: [] as $file) {
                $category = basename($categoryDir);
                $page     = basename($file, '.json');

                $pages[] = [
                    'id'       => $category . '/' . $page,
                    'category' => $category,
                    'page'     => $page,
                    'route'    => json_decode((string) file_get_contents($file), true, 512, JSON_THROW_ON_ERROR),
                ];
            }
        }

        usort($pages, static fn (array $a, array $b): int => strcmp($a['id'], $b['id']));

        return $pages;
    }

    /**
     * Resolves the path and method, cross-checking prose against the cURL sample.
     *
     * @param array<string, mixed> $route
     *
     * @return array{path: string, method: string, query: array<string, string>}|null
     */
    private function endpoint(array $route, string $pageId): ?array
    {
        $prose = $this->endpointFromProse($route);
        $curl  = $this->endpointFromCurl($route);

        if ($prose !== null && $curl !== null) {
            if ($prose['path'] !== $curl['path']) {
                $this->note(sprintf(
                    '%s: path differs - prose says `%s`, cURL sample says `%s`. Used the sample.',
                    $pageId,
                    $prose['path'],
                    $curl['path']
                ));
            }

            if ($prose['method'] !== $curl['method']) {
                $this->note(sprintf(
                    '%s: method differs - prose says %s, cURL sample says %s. Used the sample.',
                    $pageId,
                    $prose['method'],
                    $curl['method']
                ));
            }
        }

        $endpoint = $curl ?? $prose;

        if ($endpoint === null) {
            return null;
        }

        // A GET sample is never published, so prose query hints matter there.
        if ($curl !== null && $prose !== null && $prose['query'] !== [] && $curl['query'] === []) {
            $endpoint['query'] = $prose['query'];
        }

        return $endpoint;
    }

    /**
     * @param array<string, mixed> $route
     *
     * @return array{path: string, method: string, query: array<string, string>}|null
     */
    private function endpointFromProse(array $route): ?array
    {
        $blocks = $this->sectionBlocks($route, 'url-and-method');
        $url    = null;
        $method = null;

        foreach ($blocks as $block) {
            if ($block['type'] === 'code' && str_contains($block['code'], self::SERVER_URL)) {
                $url ??= trim(explode("\n", $block['code'])[0]);
                continue;
            }

            if ($block['type'] === 'text' && preg_match('/Method:?\s*\**\s*([A-Z]+)/i', HtmlDocParser::plainText($block), $matches) === 1) {
                $candidate = strtoupper($matches[1]);
                if (in_array($candidate, self::HTTP_METHODS, true)) {
                    $method ??= $candidate;
                }
            }
        }

        if ($url === null || $method === null) {
            return null;
        }

        return $this->splitUrl($url, $method);
    }

    /**
     * @param array<string, mixed> $route
     *
     * @return array{path: string, method: string, query: array<string, string>}|null
     */
    private function endpointFromCurl(array $route): ?array
    {
        foreach ($route['codeSamples'] ?? [] as $sample) {
            if (strtolower($sample['language'] ?? '') !== 'curl') {
                continue;
            }

            if (preg_match("/curl\s+-X\s+([A-Z]+)\s+'([^']+)'/", $sample['code'] ?? '', $matches) === 1) {
                return $this->splitUrl($matches[2], strtoupper($matches[1]));
            }
        }

        return null;
    }

    /**
     * @return array{path: string, method: string, query: array<string, string>}
     */
    private function splitUrl(string $url, string $method): array
    {
        $url   = trim($url);
        $query = [];

        if (str_contains($url, '?')) {
            [$url, $queryString] = explode('?', $url, 2);

            foreach (explode('&', $queryString) as $pair) {
                [$name, $value] = array_pad(explode('=', $pair, 2), 2, '');
                if ($name !== '') {
                    $query[$name] = $value;
                }
            }
        }

        $path = (string) preg_replace('#^' . preg_quote(self::SERVER_URL, '#') . '#', '', $url);
        $path = '/' . trim($path, '/');

        // The prose occasionally drops the slash before a path parameter.
        $path = (string) preg_replace('#([^/])\{#', '$1/{', $path);

        return ['path' => $path, 'method' => $method, 'query' => $query];
    }

    /**
     * @param array<string, mixed>                                          $route
     * @param array{id: string, category: string, page: string}             $page
     * @param array{path: string, method: string, query: array<string, string>} $endpoint
     *
     * @return array<string, mixed>
     */
    private function operation(array $route, array $page, array $endpoint): array
    {
        $operation = [
            'operationId' => $this->operationId($page['page']),
            'summary'     => sprintf('%s: %s', ucfirst($page['category']), $route['title']),
            'tags'        => [$page['category']],
            'externalDocs' => [
                'description' => 'Portal page',
                'url'         => sprintf('https://developer.spryng.nl/%s', $page['id']),
            ],
        ];

        $description = $this->sectionText($route, 'api-overview');
        if ($description !== '') {
            $operation['description'] = $description;
        }

        $parameters = $this->parameters($route, $endpoint);
        if ($parameters !== []) {
            $operation['parameters'] = $parameters;
        }

        $body = $this->requestBody($route, $endpoint, $page['id']);
        if ($body !== null) {
            $operation['requestBody'] = $body;
        }

        $operation['responses'] = $this->responses($route, $page['id']);

        return $operation;
    }

    /**
     * @param array<string, mixed>                                             $route
     * @param array{path: string, method: string, query: array<string, string>} $endpoint
     *
     * @return list<array<string, mixed>>
     */
    private function parameters(array $route, array $endpoint): array
    {
        $parameters = [];
        $seen       = [];

        foreach ($this->pathParameters($endpoint['path']) as $name) {
            $parameters[]  = [
                'name'     => $name,
                'in'       => 'path',
                'required' => true,
                'schema'   => ['type' => 'string'],
            ];
            $seen[strtolower($name)] = true;
        }

        foreach ($this->tables($route) as $table) {
            $kind = $this->tableKind($table, $endpoint['method']);

            if ($kind !== 'header' && $kind !== 'query') {
                continue;
            }

            foreach ($this->tableRows($table) as $row) {
                $name = $row['name'];

                // The API key is modelled as a security scheme, not a parameter.
                if (strtolower($name) === 'x-api-key' || strtolower($name) === 'content-type') {
                    continue;
                }

                if (isset($seen[strtolower($name)])) {
                    continue;
                }

                $seen[strtolower($name)] = true;
                $parameters[] = array_filter([
                    'name'        => $name,
                    'in'          => $kind === 'header' ? 'header' : 'query',
                    'required'    => $kind === 'header' ? true : ($row['required'] ?? false),
                    'description' => $row['description'],
                    'schema'      => $this->schemaForType($row['type'], $row['description']),
                ], static fn (mixed $value): bool => $value !== '' && $value !== null);
            }
        }

        foreach (array_keys($endpoint['query']) as $name) {
            if (isset($seen[strtolower($name)])) {
                continue;
            }

            $seen[strtolower($name)] = true;
            $parameters[] = [
                'name'     => $name,
                'in'       => 'query',
                'required' => true,
                'schema'   => ['type' => 'string'],
            ];
        }

        return $parameters;
    }

    /**
     * @return list<string>
     */
    private function pathParameters(string $path): array
    {
        preg_match_all('/\{([^}]+)\}/', $path, $matches);

        return $matches[1];
    }

    /**
     * @param array<string, mixed>                                             $route
     * @param array{path: string, method: string, query: array<string, string>} $endpoint
     *
     * @return array<string, mixed>|null
     */
    private function requestBody(array $route, array $endpoint, string $pageId): ?array
    {
        if (in_array($endpoint['method'], ['GET', 'DELETE'], true)) {
            return null;
        }

        $schema   = ['type' => 'object', 'properties' => []];
        $required = [];
        $found    = false;

        foreach ($this->tables($route) as $table) {
            if ($this->tableKind($table, $endpoint['method']) !== 'body') {
                continue;
            }

            foreach ($this->tableRows($table) as $row) {
                $found = true;
                $this->setProperty(
                    $schema,
                    $row['name'],
                    $this->schemaForType($row['type'], $row['description'], $row['description']),
                    $row['required'] === true
                );
            }
        }

        $example = $this->requestExample($route);

        if (!$found && $example === null) {
            return null;
        }

        if ($example !== null) {
            // The tables describe the fields that matter; the sample payload
            // usually mentions a few more. Let the tables win on type and
            // requiredness, and take the leftovers from the sample.
            $schema = $this->mergeSchemas($schema, $this->inferSchema($example));
        }

        $media = ['schema' => $schema];
        if ($example !== null) {
            $media['example'] = $example;

            foreach ($schema['required'] ?? [] as $property) {
                if (!array_key_exists($property, $example)) {
                    $this->note(sprintf(
                        '%s: `%s` is documented as required but the cURL sample leaves it out.',
                        $pageId,
                        $property
                    ));
                }
            }
        }

        return [
            'required' => true,
            'content'  => ['application/json' => $media],
        ];
    }

    /**
     * @param array<string, mixed> $route
     */
    private function requestExample(array $route): mixed
    {
        foreach ($route['codeSamples'] ?? [] as $sample) {
            if (strtolower($sample['language'] ?? '') !== 'curl') {
                continue;
            }

            if (preg_match("/-d\s+'(.*)'\s*$/s", $sample['code'] ?? '', $matches) === 1) {
                $decoded = json_decode($matches[1], true);
                if (is_array($decoded)) {
                    return $decoded;
                }
            }
        }

        return null;
    }

    /**
     * @param array<string, mixed> $route
     *
     * @return array<string, mixed>
     */
    private function responses(array $route, string $pageId): array
    {
        $responses = [];
        $status    = null;
        $summary   = '';

        foreach ($this->sectionBlocks($route, 'responses') as $block) {
            if ($block['type'] === 'code' && preg_match('/^\s*(\d{3})\b\s*(.*)$/', $block['code'], $matches) === 1) {
                $status  = $matches[1];
                $summary = trim($matches[2]);
                $responses[$status] ??= ['description' => $summary !== '' ? $summary : 'See the portal documentation.'];
                continue;
            }

            if ($status === null) {
                continue;
            }

            if ($block['type'] === 'text') {
                $text = HtmlDocParser::plainText($block);
                if ($text !== '' && ($responses[$status]['description'] ?? '') === $summary) {
                    $responses[$status]['description'] = trim($summary . ' ' . $text);
                }
                continue;
            }

            if ($block['type'] === 'code' && !isset($responses[$status]['content'])) {
                $example = json_decode($block['code'], true);

                if (!is_array($example)) {
                    // Several examples contain placeholder comments such as
                    // "{ other message data, if exists }" and cannot be parsed.
                    continue;
                }

                if ((int) $status >= 400) {
                    $this->errorExamples[] = $example;
                }

                $responses[$status]['content'] = [
                    'application/json' => [
                        'schema'  => (int) $status >= 400
                            ? ['$ref' => '#/components/schemas/ErrorResponse']
                            : $this->inferSchema($example),
                        'example' => $example,
                    ],
                ];
            }
        }

        if ($responses === []) {
            $this->note(sprintf('%s: no response codes documented.', $pageId));
            $responses['default'] = ['description' => 'Undocumented.'];
        }

        ksort($responses);

        return $responses;
    }

    /**
     * Classifies a parameter table as header, query or request-body properties.
     *
     * @param array{table: array<string, mixed>, context: string, fragment: string} $table
     */
    private function tableKind(array $table, string $method): string
    {
        $headers = array_map('strtolower', $table['table']['headers']);
        $first   = $headers[0] ?? '';
        $context = strtolower($table['context']);

        if ($first === 'header') {
            return 'header';
        }

        if ($first !== 'property' && $first !== 'parameter') {
            return 'other';
        }

        if (str_contains($context, 'query')) {
            return 'query';
        }

        if ($table['fragment'] === 'request-body' || str_contains($context, 'request body')) {
            return 'body';
        }

        return in_array($method, ['GET', 'DELETE'], true) ? 'query' : 'body';
    }

    /**
     * Every table on the page, with the prose that introduced it.
     *
     * @param array<string, mixed> $route
     *
     * @return list<array{table: array<string, mixed>, context: string, fragment: string}>
     */
    private function tables(array $route): array
    {
        $tables = [];

        foreach ($route['sections'] ?? [] as $section) {
            $fragment = $section['fragment'] ?? '';
            if ($fragment === 'responses' || $fragment === 'api-overview') {
                continue;
            }

            $context = '';

            foreach (HtmlDocParser::blocks($section['content'] ?? '') as $block) {
                if ($block['type'] === 'text') {
                    $context = HtmlDocParser::plainText($block);
                    continue;
                }

                if ($block['type'] === 'table') {
                    $tables[] = ['table' => $block, 'context' => $context, 'fragment' => $fragment];
                }
            }
        }

        return $tables;
    }

    /**
     * @param array{table: array<string, mixed>, context: string, fragment: string} $table
     *
     * @return list<array{name: string, type: string, required: bool|null, description: string}>
     */
    private function tableRows(array $table): array
    {
        $headers    = array_map('strtolower', $table['table']['headers']);
        $optional   = str_contains(strtolower($table['context']), 'optional');
        $typeIndex  = $this->columnIndex($headers, 'type');
        $reqIndex   = $this->columnIndex($headers, 'required');
        $descIndex  = $this->columnIndex($headers, 'description');
        $rows       = [];

        foreach ($table['table']['rows'] as $row) {
            $name = trim($row[0] ?? '');
            if ($name === '') {
                continue;
            }

            $requiredCell = $reqIndex !== null ? strtolower(trim($row[$reqIndex] ?? '')) : '';
            $required     = $optional ? false : ($reqIndex !== null ? $requiredCell === 'required' : null);

            $rows[] = [
                'name'        => $name,
                'type'        => $typeIndex !== null ? trim($row[$typeIndex] ?? '') : '',
                'required'    => $required,
                'description' => $descIndex !== null ? trim($row[$descIndex] ?? '') : '',
            ];
        }

        return $rows;
    }

    /**
     * @param list<string> $headers
     */
    private function columnIndex(array $headers, string $needle): ?int
    {
        foreach ($headers as $index => $header) {
            if (str_contains($header, $needle)) {
                return $index;
            }
        }

        return null;
    }

    /**
     * Writes a possibly dotted property path into a nested object schema.
     *
     * @param array<string, mixed> $schema
     * @param array<string, mixed> $definition
     */
    private function setProperty(array &$schema, string $path, array $definition, bool $required): void
    {
        $segments = explode('.', $path);
        $leaf     = array_pop($segments);
        $node     = &$schema;

        foreach ($segments as $segment) {
            $node['properties'][$segment] ??= ['type' => 'object', 'properties' => []];

            if (($node['properties'][$segment]['type'] ?? '') === 'array') {
                $node['properties'][$segment]['items'] ??= ['type' => 'object', 'properties' => []];
                $node = &$node['properties'][$segment]['items'];
                continue;
            }

            $node['properties'][$segment]['properties'] ??= [];
            $node = &$node['properties'][$segment];
        }

        $existing = $node['properties'][$leaf] ?? [];
        $node['properties'][$leaf] = $definition + $existing;

        if ($required) {
            $node['required'] = array_values(array_unique(array_merge($node['required'] ?? [], [$leaf])));
        }

        unset($node);
    }

    /**
     * @return array<string, mixed>
     */
    private function schemaForType(string $type, string $description = '', string $hint = ''): array
    {
        $normalised = strtolower(trim($type));

        $schema = match (true) {
            $normalised === 'guid'                             => ['type' => 'string', 'format' => 'uuid'],
            $normalised === 'timestamp' || $normalised === 'datetime' => ['type' => 'string', 'format' => 'date-time'],
            $normalised === 'boolean' || $normalised === 'bool' => ['type' => 'boolean'],
            $normalised === 'integer' || $normalised === 'int' || $normalised === 'number' => ['type' => 'integer'],
            $normalised === 'array' || $normalised === 'json array' => ['type' => 'array', 'items' => ['type' => 'string']],
            $normalised === 'json object' || $normalised === 'object' => ['type' => 'object'],
            default                                            => ['type' => 'string'],
        };

        $enum = $this->enumFromDescription($hint !== '' ? $hint : $description);
        if ($enum !== [] && ($schema['type'] === 'string')) {
            $schema['enum'] = $enum;
        }

        return $schema;
    }

    /**
     * Pulls "Enum e.g. A | B | C" listings out of a description.
     *
     * @return list<string>
     */
    private function enumFromDescription(string $description): array
    {
        if (preg_match('/(?:allowed (?:options|character sets)|enum)[^:.]*?(?:are|e\.g\.|:)?\s*([A-Za-z][A-Za-z ]*(?:\|[A-Za-z ]+)+)/i', $description, $matches) !== 1) {
            return [];
        }

        $values = array_values(array_filter(
            array_map('trim', explode('|', $matches[1])),
            // Guard against trailing prose such as "... | Unicode e.g." leaking in.
            static fn (string $value): bool => $value !== '' && strlen($value) > 1
        ));

        // "Auto | GSM | Unicode e.g. ..." leaves a stray "e" on the last value.
        $last = array_key_last($values);
        if ($last !== null) {
            $values[$last] = (string) preg_replace('/\s+e$/', '', $values[$last]);
        }

        return count($values) > 1 ? $values : [];
    }

    /**
     * Fills gaps in $primary with anything $secondary knows about.
     *
     * @param array<string, mixed> $primary
     * @param array<string, mixed> $secondary
     *
     * @return array<string, mixed>
     */
    private function mergeSchemas(array $primary, array $secondary): array
    {
        $merged = $primary;

        foreach ($secondary as $key => $value) {
            if ($key === 'properties' && is_array($value)) {
                foreach ($value as $name => $definition) {
                    $merged['properties'][$name] = isset($primary['properties'][$name])
                        ? $this->mergeSchemas($primary['properties'][$name], $definition)
                        : $definition;
                }
                continue;
            }

            if ($key === 'items' && is_array($value)) {
                $merged['items'] = isset($primary['items']) && is_array($primary['items'])
                    ? $this->mergeSchemas($primary['items'], $value)
                    : $value;
                continue;
            }

            if ($key === 'type' && isset($primary['type']) && $primary['type'] !== $value) {
                // The tables describe "recipients" as an array of strings where
                // the sample shows objects. Structure beats prose.
                if ($value === 'object' || $value === 'array') {
                    $merged['type'] = $value;
                    unset($merged['format'], $merged['enum']);
                }
                continue;
            }

            $merged[$key] ??= $value;
        }

        // A table can call something an array while the sample shows objects.
        if (($merged['type'] ?? '') === 'object') {
            unset($merged['items']);
        }

        if (($merged['type'] ?? '') === 'array') {
            unset($merged['properties'], $merged['required']);
        }

        return $merged;
    }

    /**
     * @return array<string, mixed>
     */
    private function inferSchema(mixed $value): array
    {
        if (is_bool($value)) {
            return ['type' => 'boolean'];
        }

        if (is_int($value)) {
            return ['type' => 'integer'];
        }

        if (is_float($value)) {
            return ['type' => 'number'];
        }

        if ($value === null) {
            return ['type' => 'string', 'nullable' => true];
        }

        if (is_string($value)) {
            return match (true) {
                preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-/i', $value) === 1 => ['type' => 'string', 'format' => 'uuid'],
                preg_match('/^\d{4}-\d{2}-\d{2}T/', $value) === 1        => ['type' => 'string', 'format' => 'date-time'],
                default                                                  => ['type' => 'string'],
            };
        }

        if (!is_array($value)) {
            return ['type' => 'string'];
        }

        if ($value === []) {
            return ['type' => 'array', 'items' => ['type' => 'string']];
        }

        if (array_is_list($value)) {
            $items = $this->inferSchema($value[0]);

            // Later entries in an example array often carry fields the first
            // one omits; fold them all together.
            foreach (array_slice($value, 1) as $entry) {
                $items = $this->mergeSchemas($items, $this->inferSchema($entry));
            }

            return ['type' => 'array', 'items' => $items];
        }

        $properties = [];
        foreach ($value as $key => $child) {
            $properties[(string) $key] = $this->inferSchema($child);
        }

        return ['type' => 'object', 'properties' => $properties];
    }

    /**
     * The shared error envelope, folded together from every 4xx/5xx example.
     *
     * @return array<string, mixed>
     */
    private function errorSchema(): array
    {
        $schema = [
            'type'       => 'object',
            'properties' => [
                'errors' => [
                    'type'  => 'array',
                    'items' => [
                        'type'       => 'object',
                        'properties' => [
                            'errorCode'    => ['type' => 'string'],
                            'errorMessage' => ['type' => 'string'],
                        ],
                        'additionalProperties' => true,
                    ],
                ],
            ],
            'additionalProperties' => true,
        ];

        foreach ($this->errorExamples as $example) {
            $schema = $this->mergeSchemas($schema, $this->inferSchema($example));
        }

        return $schema;
    }

    private function operationId(string $page): string
    {
        $slug  = (string) preg_replace('/^v\d+-/', '', $page);
        $parts = array_values(array_filter(explode('-', $slug)));
        $id    = array_shift($parts) ?? $slug;

        foreach ($parts as $part) {
            $id .= ucfirst($part);
        }

        $candidate = $id;
        $suffix    = 2;
        while (isset($this->operationIds[$candidate])) {
            $candidate = $id . $suffix++;
        }

        $this->operationIds[$candidate] = true;

        return $candidate;
    }

    /**
     * @param array<string, mixed> $route
     *
     * @return list<array<string, mixed>>
     */
    private function sectionBlocks(array $route, string $fragment): array
    {
        foreach ($route['sections'] ?? [] as $section) {
            if (($section['fragment'] ?? '') === $fragment) {
                return HtmlDocParser::blocks($section['content'] ?? '');
            }
        }

        return [];
    }

    /**
     * @param array<string, mixed> $route
     */
    private function sectionText(array $route, string $fragment): string
    {
        $texts = [];

        foreach ($this->sectionBlocks($route, $fragment) as $block) {
            if ($block['type'] === 'text') {
                $texts[] = HtmlDocParser::plainText($block);
            }
        }

        return trim(implode("\n\n", $texts));
    }

    private function revision(): string
    {
        return $this->navMenu()['version'] ?? '0.0.0';
    }

    /**
     * @param list<string> $categories
     *
     * @return list<array<string, string>>
     */
    private function tagList(array $categories): array
    {
        $titles = [];
        foreach ($this->navMenu()['categories'] ?? [] as $category) {
            $titles[$category['path']] = $category['title'];
        }

        return array_values(array_map(
            static fn (string $name): array => [
                'name'        => $name,
                'description' => sprintf(
                    'Endpoints documented under "%s" in the portal.',
                    $titles[$name] ?? $name
                ),
            ],
            $categories
        ));
    }

    /**
     * @return array<string, mixed>
     */
    private function navMenu(): array
    {
        static $navMenu = null;

        if ($navMenu === null) {
            $file    = $this->docsDir . '/raw/nav-menu.json';
            $navMenu = is_file($file)
                ? json_decode((string) file_get_contents($file), true, 512, JSON_THROW_ON_ERROR)
                : [];
        }

        return $navMenu;
    }

    /**
     * A flat method/path index next to the specification. The test suite reads
     * it to check that every documented endpoint still has a client method, so
     * a new Spryng release shows up as a failing test rather than silence.
     *
     * @param array<string, array<string, mixed>> $paths
     */
    private function writeEndpointIndex(array $paths): void
    {
        $endpoints = [];

        foreach ($paths as $path => $operations) {
            foreach ($operations as $method => $operation) {
                $endpoints[] = [
                    'method'      => strtoupper($method),
                    'path'        => $path,
                    'operationId' => $operation['operationId'] ?? '',
                ];
            }
        }

        file_put_contents(
            $this->docsDir . '/endpoints.json',
            json_encode($endpoints, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
        );
    }

    private function note(string $message): void
    {
        $this->notes[] = $message;
    }

    private function writeConflictReport(int $pathCount): void
    {
        $lines = [
            '# Documentation conflicts and gaps',
            '',
            sprintf(
                'Produced by `tools/build-openapi.php` while deriving `docs/openapi.yaml` (%d paths).',
                $pathCount
            ),
            '',
            'Each entry is a place where the portal contradicts itself or leaves something',
            'out. Verify against the live API before relying on the generated schema there.',
            '',
            'Linting the specification surfaces a handful more. Those are almost all',
            'placeholder values in Spryng\'s own samples - `"messageType": "messageType"`,',
            '`"validity": "validity"` - which cannot satisfy the enum or format the same',
            'page documents. They are left in place: the sample is what the portal shows.',
            '',
        ];

        if ($this->notes === []) {
            $lines[] = 'No conflicts found in this revision.';
        }

        foreach ($this->notes as $note) {
            $lines[] = '- ' . $note;
        }

        file_put_contents($this->docsDir . '/CONFLICTS.md', implode("\n", $lines) . "\n");
    }
}

$docsDir = rtrim($argv[1] ?? dirname(__DIR__) . '/docs/api', '/');
$output  = $argv[2] ?? dirname($docsDir) . '/openapi.yaml';

(new OpenApiBuilder($docsDir, $output))->run();
