<?php

declare(strict_types=1);

namespace Acme\SpryngMessaging\Tools;

use RuntimeException;

require __DIR__ . '/lib/HtmlDocParser.php';

/**
 * Mirrors the Spryng developer portal into docs/api/.
 *
 * developer.spryng.nl is a single-page app; its content comes from a separate,
 * unauthenticated content API. Every request needs an X-Correlation-Id header
 * holding a UUID, and nothing else:
 *
 *   GET https://devportal-data.spryng.nl/v1/dev-portal/content/revision
 *   GET https://devportal-data.spryng.nl/v1/dev-portal/content/nav-menu
 *   GET https://devportal-data.spryng.nl/v1/dev-portal/content/page/{category}/{page}
 *
 * Usage:
 *   php tools/fetch-docs.php [target-dir]      (default: docs/api)
 */
final class DocsFetcher
{
    private const BASE_URL = 'https://devportal-data.spryng.nl/v1/dev-portal';

    public function __construct(private readonly string $targetDir)
    {
    }

    public function run(): void
    {
        $revision = $this->get('content/revision')['version'] ?? 'unknown';
        $this->line(sprintf('Portal content revision: %s', $revision));

        $categories = $this->get('content/nav-menu')['categories'] ?? [];
        $index      = [];
        $pageCount  = 0;

        // The builder reads this back for the spec version and its tag names.
        $this->write('raw/nav-menu.json', json_encode(
            ['version' => $revision, 'categories' => $categories],
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        ) . "\n");

        foreach ($categories as $category) {
            foreach ($category['routes'] ?? [] as $entry) {
                $path  = $category['path'] . '/' . $entry['path'];
                $route = $this->get('content/page/' . $path)['route'] ?? null;

                if ($route === null) {
                    $this->line(sprintf('  ! no route data for %s', $path));
                    continue;
                }

                $this->write("raw/{$path}.json", json_encode(
                    $route,
                    JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
                ) . "\n");
                $this->write("{$path}.md", $this->toMarkdown($category, $entry, $route));

                $index[$category['title']][] = sprintf(
                    '- [%s](%s.md) - `%s`',
                    $entry['title'],
                    $path,
                    $path
                );
                $pageCount++;
            }
        }

        $this->write('README.md', $this->indexMarkdown($revision, $index, $pageCount));
        $this->line(sprintf('Wrote %d pages to %s', $pageCount, $this->targetDir));
    }

    /**
     * @param array<string, mixed> $category
     * @param array<string, mixed> $entry
     * @param array<string, mixed> $route
     */
    private function toMarkdown(array $category, array $entry, array $route): string
    {
        $source = sprintf('https://developer.spryng.nl/%s/%s', $category['path'], $entry['path']);
        $lines  = [
            sprintf('# %s / %s', $category['title'], $entry['title']),
            '',
            sprintf('Source: <%s>', $source),
            '',
            'Generated by `tools/fetch-docs.php`. Do not edit by hand.',
            '',
        ];

        foreach ($route['sections'] ?? [] as $section) {
            $lines[] = '## ' . $section['title'];
            $lines[] = '';
            $lines[] = HtmlDocParser::toMarkdown(HtmlDocParser::blocks($section['content'] ?? ''));
            $lines[] = '';
        }

        foreach ($route['codeSamples'] ?? [] as $sample) {
            $lines[] = '## Code sample: ' . $sample['language'];
            $lines[] = '';
            $lines[] = '```' . $this->fenceLanguage($sample['language']);
            $lines[] = trim($sample['code'] ?? '');
            $lines[] = '```';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * @param array<string, list<string>> $index
     */
    private function indexMarkdown(string $revision, array $index, int $pageCount): string
    {
        $lines = [
            '# Spryng API documentation mirror',
            '',
            sprintf('Portal content revision: `%s` (%d pages).', $revision, $pageCount),
            '',
            'A local copy of <https://developer.spryng.nl>, fetched from the portal',
            'content API by `tools/fetch-docs.php`. `openapi.yaml` in the parent',
            'directory is derived from the `raw/` payloads by `tools/build-openapi.php`.',
            '',
            'Everything here is generated. Re-run the fetcher instead of editing.',
            '',
        ];

        foreach ($index as $title => $entries) {
            $lines[] = '## ' . $title;
            $lines[] = '';
            $lines   = array_merge($lines, $entries);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function fenceLanguage(string $language): string
    {
        return match (strtolower($language)) {
            'curl'   => 'bash',
            'nodejs' => 'javascript',
            'c#'     => 'csharp',
            default  => strtolower($language),
        };
    }

    /**
     * @return array<string, mixed>
     */
    private function get(string $path): array
    {
        $url     = self::BASE_URL . '/' . $path;
        $headers = ['X-Correlation-Id: ' . $this->uuid4(), 'Accept: application/json'];

        $handle = curl_init($url);
        curl_setopt_array($handle, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER     => $headers,
            CURLOPT_TIMEOUT        => 30,
        ]);

        $body   = curl_exec($handle);
        $status = curl_getinfo($handle, CURLINFO_RESPONSE_CODE);
        $error  = curl_error($handle);
        curl_close($handle);

        if (!is_string($body)) {
            throw new RuntimeException(sprintf('GET %s failed: %s', $url, $error));
        }

        if ($status !== 200) {
            throw new RuntimeException(sprintf('GET %s returned HTTP %d: %s', $url, $status, $body));
        }

        $decoded = json_decode($body, true, 512, JSON_THROW_ON_ERROR);

        return $decoded['data'] ?? [];
    }

    private function uuid4(): string
    {
        $bytes    = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);

        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($bytes), 4));
    }

    private function write(string $relativePath, string $contents): void
    {
        $target    = $this->targetDir . '/' . $relativePath;
        $directory = dirname($target);

        if (!is_dir($directory) && !mkdir($directory, 0o755, true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf('Could not create %s', $directory));
        }

        file_put_contents($target, $contents);
    }

    private function line(string $message): void
    {
        fwrite(STDOUT, $message . PHP_EOL);
    }
}

$target = $argv[1] ?? dirname(__DIR__) . '/docs/api';
(new DocsFetcher(rtrim($target, '/')))->run();
